# Generated by Django 3.0.4 on 2020-04-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(default='spain', max_length=20),
            preserve_default=False,
        ),
    ]
