# Generated by Django 3.0.4 on 2020-04-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20200420_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
    ]
